# workflow params
num_predict_batch_process: 2
num_gen_winning_prob_cal_data_processes: 1
predict_batch_size: 1
game_loop_thread_multiple: 1
num_train_eval_process: 1
eval_task_num_games: 10
historical_data_filename: data/nil

# train process params
first_train_data_step: 10
train_per_step: 2
eval_model_per_step: 30
log_step_num: 5

# game params
num_mcts_simulation_per_step: 800
mcts_c_puct: 1
mcts_tau: 1
mcts_log_to_file: True

# model params
model_param_dict:
    device: 'cpu'
    batch_size: 8
    embedding_dim: 64
    positional_embedding_dim: 32
    transformer_head_dim: 16
    num_layers: 2

# simulation params
simulation_recurrent_params:
  0:
    -
      -
        - 7
        - 100
        - True
    - 100
  1:
    -
      -
        - 4
        - 100
        - True
    - 100
  2:
    -
      -
        - 3
        - 100
        - True
    - 100
  3:
    -
      -
        - 2
        - 100
        - True
    - 100