# workflow params
num_predict_batch_process: 2
num_gen_winning_prob_cal_data_processes: 1
predict_batch_size: 1
game_loop_thread_multiple: 1
num_train_eval_process: 1
eval_task_num_games: 10
historical_data_filename: data/nil

# train process params
first_train_data_step: 10
train_per_step: 1000
eval_model_per_step: 100
log_step_num: 5

# game params
num_mcts_simulation_per_step: 1000
mcts_c_puct: 1.7
mcts_tau: 0.5
mcts_dirichlet_noice_epsilon: 0.3

# model params
model_param_dict:
    device: 'cpu'

# simulation params
simulation_recurrent_params:
  0:
    -
      -
        - 7
        - 100
        - True
    - 100
  1:
    -
      -
        - 4
        - 100
        - True
    - 100
  2:
    -
      -
        - 3
        - 100
        - True
    - 100
  3:
    -
      -
        - 2
        - 100
        - True
    - 100