# workflow params
num_predict_batch_process: 2
num_gen_winning_prob_cal_data_processes: 16
predict_batch_size: 8
game_loop_thread_multiple: 2.5
num_train_eval_process: 5
eval_task_num_games: 1000
update_model_bb_per_100_thres: 5.
historical_data_filename: data/history.txt

# train process params
first_train_data_step: 500
train_per_step: 4
eval_model_per_step: 5000
log_step_num: 200

# game params
small_blind: 25
big_blind: 50
# puct越大，对N（mcts节点选择次数）系数影响越大，对模型概率预测影响越大，即对“应该选哪个”（直觉）的相对影响越大，对环境反馈（客观事实）的相对影响就越小。
# 所以原则是：在保持模型和N的影响力的前提下（即结合场景调节对环境反馈的系数，这也让MCTS有效），尽量减小。1以减小num_mcts_simulation_per_step，即减少算力；2以减小模型badcase对后续训练数据的影响（对某一个类过高的直觉估计会导致过多执行该类，即在训练数据中N变大）。
# 如何判断puct的影响力有效：
# 1. 看N，每个类最重要保证一定的统计意义
# 2. 看R，每个类最终要拉到很接近的数值上
# 3. 看Q，每个类最终要符合环境的物理意义
num_mcts_simulation_per_step: 800
mcts_c_puct: 0.8
mcts_tau: 3
mcts_dirichlet_noice_epsilon: 0.1  # 增加随机性，避免模型过于依赖历史数据。注意避免过大noise导致数据过脏，训练难以收敛
mcts_model_Q_epsilon: 0.01  # 当模型更有效后，适当调大这个值
mcts_choice_method: 'probability'  # choices: 'argmax', 'probability'
mcts_log_to_file: False

# model params
num_bins: 10
model_param_dict:
    n_observation: 5
    n_actions: 4
    num_output_class: 12
    device: 'cuda:0'
    embedding_dim: 128
    positional_embedding_dim: 128
    transformer_head_dim: 64
    num_layers: 4
    historical_action_sequence_length: 16
    epsilon: 0.05
    epsilon_max: 0.8
    gamma: 0.9
    batch_size: 64
    base_learning_rate: 0.000001
    max_learning_rate: 0.00001
    step_size_up: 1000
    step_size_down: 4000
    l2_weight: 0.0
    num_bins: 10
    save_train_data: True
    # 要保证足够大，以使模型迭代过程以一种渐变的方式进行（包含历史数据），保证v和v-1版本模型保持一定连贯性，可令新模型结果不会太差。
    # 建议大于eval_model_per_step * train_per_step * 2
    transition_buffer_len: 50000
    num_inference_per_step: 500   # show prediction result per steps
    num_data_print_per_inference: 5  # number of result to print per inference

# simulation params
simulation_recurrent_params:
  0:
    -
      -
        - 1
        - 0
        - False
      -
        - 1
        - 0
        - False
      -
        - 1
        - 0
        - True
      -
        - 4
        - 5
        - True
    - 98000
  1:
    -
      -
        - 1
        - 0
        - True
      -
        - 1
        - 0
        - True
      -
        - 2
        - 45
        - True
    - 97290
  2:
    -
      -
        - 1
        - 0
        - True
      -
        - 1
        - 0
        - False
      -
        - 1
        - 0
        - True
    - 45540
  3:
    -
      -
        - 1
        - 0
        - False
      -
        - 1
        - 0
        - True
    - 990

# checkpoints
model_init_checkpoint_path: models/tiny_train.pth
model_last_checkpoint_path: models/last.pth
model_eval_snapshot_path_format: models/eval_%s.pth
model_best_checkpoint_path: models/best.pth