# workflow params
num_predict_batch_process: 2
num_gen_winning_prob_cal_data_processes: 10
predict_batch_size: 4
game_loop_thread_multiple: 2.5
num_train_eval_process: 5
eval_task_num_games: 1000
update_model_bb_per_100_thres: 5.
historical_data_filename: data/history.txt

# train process params
first_train_data_step: 500
train_per_step: 8
eval_model_per_step: 5000
log_step_num: 200
num_inference_per_step: 500   # show prediction result per steps
num_data_print_per_inference: 5  # number of result to print per inference

# game params
small_blind: 25
big_blind: 50
num_mcts_simulation_per_step: 800
mcts_c_puct: 1
mcts_tau: 1
mcts_dirichlet_noice_epsilon: 0.3
mcts_model_Q_epsilon: 0.01
mcts_log_to_file: False

# model params
num_bins: 10
model_param_dict:
    n_observation: 5
    n_actions: 4
    num_output_class: 22
    device: 'cuda:0'
    embedding_dim: 512
    positional_embedding_dim: 128
    transformer_head_dim: 64
    num_layers: 16
    historical_action_sequence_length: 16
    epsilon: 0.05
    epsilon_max: 0.8
    gamma: 0.9
    batch_size: 256
    base_learning_rate: 0.000001
    max_learning_rate: 0.0001
    step_size_up: 1000
    step_size_down: 4000
    l2_weight: 0.0
    num_bins: 10
    save_train_data: True
    transition_buffer_len: 10000

# simulation params
simulation_recurrent_params:
  0:
    -
      -
        - 1
        - 0
        - False
      -
        - 1
        - 0
        - False
      -
        - 1
        - 0
        - True
      -
        - 4
        - 5
        - True
    - 98000
  1:
    -
      -
        - 1
        - 0
        - True
      -
        - 1
        - 0
        - True
      -
        - 2
        - 45
        - True
    - 97290
  2:
    -
      -
        - 1
        - 0
        - True
      -
        - 1
        - 0
        - False
      -
        - 1
        - 0
        - True
    - 45540
  3:
    -
      -
        - 1
        - 0
        - False
      -
        - 1
        - 0
        - True
    - 990

# checkpoints
model_init_checkpoint_path: models/default_train.pth
model_last_checkpoint_path: models/last.pth
model_eval_snapshot_path_format: models/eval_%s.pth
model_best_checkpoint_path: models/best.pth