# workflow params
num_predict_batch_process: 2
predict_batch_size: 4
game_loop_thread_multiple: 5
num_train_eval_process: 10
train_data_path: data/history.txt
task_id: 512_64_12_3e-3_1e-2_50k

# train process params
log_step_num: 200
predict_step_num: 500
num_train_steps: 50000

# model params
model_param_dict:
    device: 'cuda:0'
    embedding_dim: 512
    positional_embedding_dim: 64
    num_transformer_head: 11
    num_layers: 12
    batch_size: 64
    learning_rate: 0.003
    l2_weight: 0.01

# checkpoints
model_test_checkpoint_path: models/test_train.pth