# workflow params
num_predict_batch_process: 1

#num_mcts_simulation_per_step: 20
#mcts_c_puct: 0.3
#mcts_tau: 1
mcts_log_to_file: True

# model params
model_param_dict:
    device: 'cpu'

# checkpoints
model_init_checkpoint_path: models/best.pth