# workflow params
num_choices: 10
num_predict_batch_process: 2
predict_batch_size: 4
game_loop_thread_multiple: 2.5
num_train_eval_process: 5
eval_task_num_games: 1000
train_data_path: data/history.txt

# train process params
log_step_num: 200   # show loss per steps
predict_step_num: 500   # show prediction result per steps
num_train_steps: 50000  # train until steps

# model params
model_param_dict:
    device: 'cuda:0'
    embedding_dim: [256, 512]
    positional_embedding_dim: [64, 128]
    num_layers: [6, 8, 10]
    batch_size: 64
    learning_rate: [0.00003, 0.0001, 0.0003]
    l2_weight: [0.001, 0.005]
    save_train_data: False

# checkpoints
model_save_checkpoint_path_format: models/test_train_%d.pth
model_eval_snapshot_path_format: models/test_train_%d_eval.pth