# workflow params
num_predict_batch_process: 1

mcts_c_puct: 2
mcts_tau: 3
mcts_log_to_file: True

# model params
model_param_dict:
    device: 'cpu'

# checkpoints
model_init_checkpoint_path: models/best.pth